services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./data:/space
    environment:
      - SB_USER=${USERNAME}:${PASSWORD}
    ports:
      - 127.0.0.1:3060:3000
