services:
  filebrowser:
    image: filebrowser/filebrowser:v2.55.0
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./data:/srv
      - /home/chris/Documents/Sync:/srv/Sync
      - ./db:/database
      - ./config:/config
    ports:
      - 127.0.0.1:3070:80
