services:
  miniflux:
    image: miniflux/miniflux:2.2.16
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    user: 3010:3010
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_DATABASE}?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - 127.0.0.1:3010:8080
  db:
    image: postgres:18.1
    restart: unless-stopped
    user: 3011:3011
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      start_period: 2m
      interval: 10s
