services:
  vaultwarden:
    image: vaultwarden/server:1.35.2
    restart: unless-stopped
    user: 1000:1000
    environment:
      DOMAIN: "https://vaultwarden.e6.freeddns.org"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - ./data/:/data/
    ports:
      - 127.0.0.1:3050:80
