services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.6
    restart: unless-stopped
    depends_on:
      - broker
    user: 3040:3040
    ports:
      - "127.0.0.1:3040:8000"
    healthcheck:
      test:
        ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      start_period: 2m
      interval: 10s
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      TZ: ${PAPERLESS_TIME_ZONE}
      PAPERLESS_REDIS: redis://broker:6379
  broker:
    image: docker.io/library/redis:8.4.0
    restart: unless-stopped
    user: 3041:3041
    volumes:
      - ./redis:/data
