services:
  syncthing:
    image: syncthing/syncthing
    restart: unless-stopped
    user: 3050:3050
    volumes:
      - ./config:/var/syncthing/config
      - ./media:/var/syncthing
      - ../paperless-chris/media/documents/archive:/var/syncthing/Paperless:ro
    ports:
      - 127.0.0.1:3050:8384
      - 10722:22000
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
